# Generated by Django 3.1 on 2020-12-02 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='last_lname',
            new_name='last_name',
        ),
    ]
